### ISSUE TITLE
block screen appears on block on app

### ISSUE THREAD

**Issue by RosmaryFC** [RosmaryFC/Focus-App#37]
when app is blocked and block screen appears, if user tried to go back to block on app, the same screen appears.

**Comment by hyunj0** [comment]
it appears that adding a nohistory attribute to the blocker activity does the trick. https://github.com/RosmaryFC/Focus-App/pull/40

**Comment by hyunj0** [comment]
did some more research as the previous solution still had the same issue. hopefully this works. https://github.com/RosmaryFC/Focus-App/pull/43
